// types/session.ts

/**
 * Learning modes that match cognitive demands of different word types.
 * Users never see these labels—they experience the difference.
 */
export enum SessionMode {
  CONTRAST = "contrast",      // Meaning vs incorrect usage
  HIERARCHY = "hierarchy",    // Spectrum or layers
  PERSONA = "persona",        // Who would use it and how
  MAP = "map",                // Visual links to related concepts
  NARRATIVE = "narrative"     // Micro-story the learner edits
}

/**
 * Different words carry different cognitive demands.
 */
export enum WordCognitiveWeight {
  INTELLECTUAL = "intellectual",      // Requires conceptual framework
  EMOTIONAL = "emotional",            // Demands emotional/social lens
  RELATIONAL = "relational",          // Abstract relational approach
  DISCRIMINATIVE = "discriminative"   // Subtle discrimination exercise
}

/**
 * Varied UI patterns to prevent rhythm prediction.
 * All interactions remain single-action per screen. No clutter.
 */
export enum DisplayFormat {
  CARD = "card",
  SLIDER = "slider",
  TWO_CHOICE = "two_choice",
  FILL_IN = "fill_in",
  DRAG_CONNECT = "drag_connect",
  SCENARIO_PICKER = "scenario_picker"
}

/**
 * The anchoring question—adaptive to word nature.
 * Principle: anchor = personal identity, not grammatical form.
 */
export interface AnchorPrompt {
  promptText: string;
  focus: "lived_experience" | "context" | "enabler" | "outcome" | "relational";
}

/**
 * Represents a word with its cognitive profile.
 */
export interface WordProfile {
  text: string;
  definition: string;
  cognitiveWeight: WordCognitiveWeight;
  semanticField: string;  // Domain: emotional, academic, technical, etc.
  contextTags: string[];  // Additional context markers
}

/**
 * Session interaction generated by a mode.
 */
export interface SessionInteraction {
  mode: string;
  word: string;
  anchor: string;
  display: string;
  task: {
    type: string;
    prompt: string;
    [key: string]: any;
  };
}

/**
 * Session context tracks progression across words.
 */
export interface SessionContext {
  previousFormats: DisplayFormat[];
  sessionHistory: Array<{
    mode: string;
    word: string;
    format: string;
  }>;
}

/**
 * Learner journey analysis results.
 */
export interface JourneyAnalysis {
  progression: "building" | "emerging" | "coherent";
  modeDiversity: number;
  journeyQuality: "developing" | "category-defining";
}

/**
 * User's response to an interaction.
 */
export interface InteractionResponse {
  interactionId: string;
  selectedOption?: string;
  userInput?: string;
  isCorrect?: boolean;
  timeSpent?: number;
  timestamp: number;
}

/**
 * Session progress tracking.
 */
export interface SessionProgress {
  currentIndex: number;
  totalInteractions: number;
  completedInteractions: number;
  responses: InteractionResponse[];
  startTime: number;
  lastInteractionTime: number;
}

/**
 * Journey metrics for analytics.
 */
export interface JourneyMetrics {
  wordsExplored: Array<{
    word: string;
    mode: string;
    cognitiveWeight: string;
  }>;
  modesUsed: string[];
  averageTimePerInteraction: number;
  journeyQuality: JourneyAnalysis;
  totalDuration: number;
}

/**
 * Props for display format components.
 */
export interface DisplayComponentProps {
  interaction: SessionInteraction;
  onComplete: (response: InteractionResponse) => void;
  interactionId: string;
}
