const wordAnchorExamples: Record<string, Record<string, string>> = {
  'Zeitgeist': {
    'Culture': 'When Zeitgeist shapes culture',
    'Society': 'When Zeitgeist shapes society',
    'History': 'When Zeitgeist shapes history',
    'Values': 'When Zeitgeist demonstrates real value',
  },
  'actual': {
    'Language Learning': 'When learning the actual difference between similar words finally clicks',
    'False Friends': 'When you discover the actual meaning of a false friend word',
    'Communication': 'When saying what\'s actual and true strengthens your credibility',
    'Identity': 'When showing your actual self helps others understand who you really are',
  },
  'actually': {
    'Meetings': 'When actually shapes meetings',
    'Misunderstandings': 'When actually shapes misunderstandings',
    'Conflict': 'When actually shapes conflict',
    'Communication': 'When actually shapes communication',
  },
  'alexithymia': {
    'Emotional Literacy': 'When alexithymia provides genuine support',
    'Reflection': 'When alexithymia shapes reflection',
    'Communication': 'When alexithymia shapes communication',
    'Growth': 'When alexithymia shapes growth',
  },
  'ambivalence': {
    'Decisions': 'When ambivalence shapes decisions',
    'Values': 'When ambivalence shapes values',
    'Conflict': 'When ambivalence shapes conflict',
    'Self-Insight': 'When ambivalence shapes self-insight',
  },
  'ambivalent': {
    'Emotion': 'When ambivalent feelings pull you in opposite directions simultaneously',
    'Decision Making': 'When staying ambivalent keeps you stuck between two good choices',
    'Relationships': 'When you feel ambivalent about someone you care for',
    'Growth': 'When ambivalence signals you need to understand yourself better',
  },
  'ameliorate': {
    'Problem Solving': 'When ameliorate shapes problem solving',
    'Improvement': 'When ameliorate shapes improvement',
    'Leadership': 'When ameliorate shapes leadership',
    'Action': 'When ameliorate shapes action',
  },
  'anachronistic': {
    'History': 'When anachronistic details reveal research gaps',
    'Literature': 'When an author includes anachronistic elements that break immersion',
    'Film': 'When anachronistic props distract from storytelling',
    'Culture': 'When something anachronistic signals outdated thinking',
  },
  'anhedonia': {
    'Mood': 'When anhedonia shapes mood',
    'Recovery': 'When anhedonia shapes recovery',
    'Habits': 'When anhedonia shapes habits',
    'Self-Care': 'When anhedonia shapes self-care',
  },
  'anthropogenic': {
    'Human Impact': 'When you witness the anthropogenic effects reshaping the world',
    'Environment': 'When your relationship with nature shifts due to anthropogenic change',
    'Responsibility': 'When you realize your role in causing anthropogenic damage',
    'Action': 'When crisis demands action against anthropogenic harm',
  },
  'appreciate': {
    'Gratitude': 'When appreciate shapes gratitude',
    'Teamwork': 'When appreciate shapes teamwork',
    'Relationships': 'When appreciate shapes relationships',
    'Support': 'When appreciate shapes support',
  },
  'artefact': {
    'Bias': 'When artefact shapes bias',
    'Reflection': 'When artefact shapes reflection',
    'Learning': 'When artefact shapes learning',
    'Objectivity': 'When artefact shapes objectivity',
  },
  'assertive': {
    'Meetings': 'When assertive shapes meetings',
    'Conflict': 'When assertive shapes conflict',
    'Confidence': 'When assertive shapes confidence',
    'Communication': 'When assertive shapes communication',
  },
  'assist': {
    'Workplace Relationships': 'When assist shapes workplace relationships',
    'Tone': 'When assist shapes tone',
    'Friendliness': 'When assist shapes friendliness',
    'Professional Distance': 'When assist shapes professional distance',
  },
  'asymmetry': {
    'Imbalance': 'When asymmetry shapes imbalance',
    'Power': 'When asymmetry shapes power',
    'Inequality': 'When asymmetry shapes inequality',
    'Awareness': 'When asymmetry shapes awareness',
  },
  'attenuate': {
    'Time': 'When attenuate marks a defining moment',
    'Emotion': 'When attenuate shapes emotion',
    'Healing': 'When attenuate shapes healing',
    'Perspective': 'When attenuate shapes perspective',
  },
  'bane': {
    'Work Habits': 'When procrastination becomes the bane of your progress',
    'Personal Growth': 'When you identify the bane holding you back',
    'Challenges': 'When a persistent bane tests your resilience',
    'Obstacles': 'When the bane you face keeps returning',
  },
  'benchmark': {
    'Personal Goals': 'When you use a benchmark to know if you\'re actually getting closer to your goal',
    'Competition': 'When a benchmark shows you where you stand against your competition',
    'Self-Assessment': 'When an honest benchmark reveals both your strengths and gaps',
    'Progress': 'When consistent benchmarking proves your improvement over time',
  },
  'biodiversity': {
    'Variety': 'When biodiversity shapes variety',
    'Health': 'When biodiversity shapes health',
    'Connections': 'When biodiversity shapes connections',
    'Strength': 'When biodiversity shapes strength',
  },
  'blithe': {
    'Youth': 'When blithe shapes youth',
    'Relationship': 'When blithe deepens your relationships',
    'Warning Ignored': 'When blithe shapes warning ignored',
    'Responsibility': 'When blithe shapes responsibility',
  },
  'broach': {
    'Communication': 'When broach shapes communication',
    'Courage': 'When broach shapes courage',
    'Relationships': 'When broach shapes relationships',
    'Honesty': 'When broach shapes honesty',
  },
  'candid': {
    'Communication': 'When candid shapes communication',
    'Growth': 'When candid shapes growth',
    'Relationships': 'When candid shapes relationships',
    'Honesty': 'When candid shapes honesty',
  },
  'carbon sink': {
    'Balance': 'When carbon sink shapes balance',
    'Absorption': 'When carbon sink shapes absorption',
    'Protection': 'When carbon sink shapes protection',
    'Stability': 'When carbon sink shapes stability',
  },
  'circumscribe': {
    'Constraint': 'When circumscribe shapes constraint',
    'Creativity': 'When circumscribe shapes creativity',
    'Boundaries': 'When circumscribe shapes boundaries',
    'Adaptation': 'When circumscribe shapes adaptation',
  },
  'cleave': {
    'Family': 'When cleave shapes family',
    'Partnership': 'When cleave shapes partnership',
    'Friendship': 'When cleave shapes friendship',
    'Creative Collaboration': 'When cleave shapes creative collaboration',
  },
  'cohesion': {
    'Unity': 'When cohesion shapes unity',
    'Community': 'When cohesion shapes community',
    'Bonds': 'When cohesion shapes bonds',
    'Belonging': 'When cohesion shapes belonging',
  },
  'complicity': {
    'Accountability': 'When complicity shapes accountability',
    'Systems': 'When complicity shapes systems',
    'Responsibility': 'When complicity shapes responsibility',
    'Ethics': 'When complicity shapes ethics',
  },
  'concern': {
    'Feedback': 'When concern shapes feedback',
    'Care': 'When concern shapes care',
    'Criticism': 'When concern shapes criticism',
    'Relationships': 'When concern deepens your relationships',
  },
  'concerning': {
    'Performance Review': 'When concerning shapes performance review',
    'Feedback': 'When concerning shapes feedback',
    'Work Anxiety': 'When concerning shapes work anxiety',
    'Communication': 'When concerning transforms how you speak',
  },
  'conflate': {
    'Precision': 'When conflate shapes precision',
    'Language': 'When conflate shapes language',
    'Critical Thinking': 'When conflate shapes critical thinking',
    'Clarity': 'When conflate shapes clarity',
  },
  'consequential': {
    'Impact': 'When consequential shapes impact',
    'Importance': 'When consequential shapes importance',
    'Choice': 'When consequential shapes choice',
    'Life Direction': 'When consequential shapes life direction',
  },
  'contingent': {
    'Planning': 'When contingent shapes planning',
    'Uncertainty': 'When contingent shapes uncertainty',
    'Decision Making': 'When contingent shapes decision making',
    'Future': 'When contingent shapes future',
  },
  'cordial': {
    'Workplace': 'When cordial shapes workplace',
    'Networking': 'When cordial shapes networking',
    'Social Events': 'When cordial shapes social events',
    'Customer Service': 'When cordial shapes customer service',
  },
  'corroborate': {
    'Validation': 'When corroborate shapes validation',
    'Truth': 'When corroborate shapes truth',
    'Evidence': 'When corroborate shapes evidence',
    'Support': 'When corroborate provides genuine support',
  },
  'critical': {
    'Work Email': 'When critical shapes work email',
    'Feedback': 'When critical shapes feedback',
    'Anxiety': 'When critical shapes anxiety',
    'Miscommunication': 'When critical shapes miscommunication',
  },
  'culpable': {
    'Accountability': 'When culpable shapes accountability',
    'Integrity': 'When culpable shapes integrity',
    'Responsibility': 'When culpable shapes responsibility',
    'Growth': 'When culpable accelerates your growth',
  },
  'degenerate': {
    'Strategy': 'When degenerate shapes strategy',
    'Equivalence': 'When degenerate shapes equivalence',
    'Insight': 'When degenerate shapes insight',
    'Efficiency': 'When degenerate shapes efficiency',
  },
  'delegation': {
    'Leadership': 'When delegation transforms you from doer to multiplier',
    'Team Management': 'When you build trust through delegation that empowers',
    'Projects': 'When smart delegation gets better results than solo effort',
    'Learning': 'When delegation teaches you to let go and trust others',
  },
  'depletion': {
    'Sustainability': 'When depletion shapes sustainability',
    'Limits': 'When depletion shapes limits',
    'Energy': 'When depletion shapes energy',
    'Balance': 'When depletion shapes balance',
  },
  'derivative': {
    'Art': 'When derivative fuels creative expression',
    'Creativity': 'When derivative fuels creative expression',
    'Criticism': 'When derivative shapes criticism',
    'Culture': 'When derivative shapes culture',
  },
  'desensitised': {
    'Boundaries': 'When desensitised shapes boundaries',
    'Adaptation': 'When desensitised shapes adaptation',
    'Media': 'When desensitised shapes media',
    'Wellbeing': 'When desensitised shapes wellbeing',
  },
  'desertification': {
    'Degradation': 'When desertification shapes degradation',
    'Neglect': 'When desertification shapes neglect',
    'Warning': 'When desertification shapes warning',
    'Care': 'When desertification shapes care',
  },
  'didactic': {
    'Teaching': 'When didactic shapes teaching',
    'Art': 'When didactic shapes art',
    'Literature': 'When didactic shapes literature',
    'Learning': 'When didactic shapes learning',
  },
  'discern': {
    'Observation': 'When discern shapes observation',
    'Judgment': 'When discern shapes judgment',
    'Insight': 'When discern shapes insight',
    'Understanding': 'When discern shapes understanding',
  },
  'discuss': {
    'Meetings': 'When discuss shapes meetings',
    'Conflict': 'When discuss shapes conflict',
    'Decision Making': 'When discuss shapes decision making',
    'Communication': 'When discuss shapes communication',
  },
  'disinterested': {
    'Fairness': 'When disinterested shapes fairness',
    'Judgment': 'When disinterested shapes judgment',
    'Conflict': 'When disinterested shapes conflict',
    'Impartiality': 'When disinterested fuels creative expression',
  },
  'dissociation': {
    'Coping': 'When dissociation shapes coping',
    'Safety': 'When dissociation shapes safety',
    'Presence': 'When dissociation shapes presence',
    'Regulation': 'When dissociation shapes regulation',
  },
  'distill': {
    'Analysis': 'When distill shapes analysis',
    'Clarity': 'When distill brings clarity',
    'Communication': 'When distill transforms how you speak',
    'Understanding': 'When distill shapes understanding',
  },
  'dogma': {
    'Beliefs': 'When dogma shapes beliefs',
    'Authority': 'When dogma shapes authority',
    'Critical Thinking': 'When dogma shapes critical thinking',
    'Growth': 'When dogma shapes growth',
  },
  'dogwhistle': {
    'Language': 'When dogwhistle shapes language',
    'Codes': 'When dogwhistle shapes codes',
    'Awareness': 'When dogwhistle shapes awareness',
    'Interpretation': 'When dogwhistle shapes interpretation',
  },
  'dysphoria': {
    'Mood': 'When dysphoria clouds everything with persistent unease',
    'Self-Monitoring': 'When you track the dysphoria patterns emerging',
    'Wellbeing': 'When dysphoria erodes the foundation of your wellbeing',
    'Awareness': 'When awareness helps you name the dysphoria you\'re feeling',
  },
  'elegiac': {
    'Art': 'When elegiac fuels creative expression',
    'Literature': 'When elegiac shapes literature',
    'Memory': 'When elegiac shapes memory',
    'Emotion': 'When elegiac shapes emotion',
  },
  'elide': {
    'Communication': 'When elide shapes communication',
    'Honesty': 'When elide shapes honesty',
    'Avoidance': 'When elide shapes avoidance',
    'Tact': 'When elide shapes tact',
  },
  'elucidate': {
    'Learning': 'When elucidate shapes learning',
    'Teaching': 'When elucidate shapes teaching',
    'Clarity': 'When elucidate shapes clarity',
    'Understanding': 'When elucidate shapes understanding',
  },
  'emergent': {
    'Systems': 'When emergent shapes systems',
    'Teams': 'When emergent shapes teams',
    'Complexity': 'When emergent shapes complexity',
    'Observation': 'When emergent shapes observation',
  },
  'empathy': {
    'Friend': 'When empathy shapes friend',
    'Family': 'When empathy shapes family',
    'Teacher': 'When empathy shapes teacher',
    'Stranger': 'When empathy shapes stranger',
  },
  'empirical': {
    'Learning': 'When empirical evidence from experience teaches you more than theory',
    'Testing': 'When empirical methods reveal what actually works',
    'Science': 'When empirical observation becomes the foundation of understanding',
    'Growth': 'When empirical results from your experiments guide your growth',
  },
  'enormity': {
    'History': 'When enormity shapes history',
    'Morality': 'When enormity guides ethical choices',
    'Justice': 'When enormity demands fairness',
    'Understanding': 'When enormity shapes understanding',
  },
  'entitlement': {
    'Privilege': 'When entitlement shapes privilege',
    'Self-Examination': 'When entitlement shapes self-examination',
    'Expectations': 'When entitlement shapes expectations',
    'Awareness': 'When entitlement shapes awareness',
  },
  'equivocal': {
    'Communication': 'When equivocal transforms how you speak',
    'Ambiguity': 'When equivocal shapes ambiguity',
    'Honesty': 'When equivocal shapes honesty',
    'Language': 'When equivocal transforms how you speak',
  },
  'equivocation': {
    'Honesty': 'When equivocation shapes honesty',
    'Communication': 'When equivocation transforms how you speak',
    'Accountability': 'When equivocation shapes accountability',
    'Self-Awareness': 'When equivocation shapes self-awareness',
  },
  'eutrophication': {
    'Balance': 'When eutrophication shapes balance',
    'Excess': 'When eutrophication shapes excess',
    'Consequences': 'When eutrophication shapes consequences',
    'Systems': 'When eutrophication shapes systems',
  },
  'eventually': {
    'Language Learning': 'When eventually shapes language learning',
    'Mistakes': 'When eventually shapes mistakes',
    'Growth': 'When eventually shapes growth',
    'Communication': 'When eventually shapes communication',
  },
  'exculpatory': {
    'Judgment': 'When exculpatory shapes judgment',
    'Fairness': 'When exculpatory shapes fairness',
    'Perspective': 'When exculpatory shapes perspective',
    'Justice': 'When exculpatory shapes justice',
  },
  'exigent': {
    'Urgency': 'When exigent shapes urgency',
    'Crisis': 'When exigent shapes crisis',
    'Decision Making': 'When exigent shapes decision making',
    'Leadership': 'When exigent shapes leadership',
  },
  'expedient': {
    'Decisions': 'When expedient shapes decisions',
    'Compromise': 'When expedient shapes compromise',
    'Integrity': 'When expedient tests your integrity',
    'Pragmatism': 'When expedient shapes pragmatism',
  },
  'expert': {
    'Professional Skill': 'When expert sharpens your skills',
    'Hobby': 'When expert shapes hobby',
    'Creative Pursuit': 'When expert shapes creative pursuit',
    'Life Experience': 'When expert shapes life experience',
  },
  'externality': {
    'Consequences': 'When externality shapes consequences',
    'Responsibility': 'When externality shapes responsibility',
    'Impact': 'When externality shapes impact',
    'Awareness': 'When externality shapes awareness',
  },
  'extrapolate': {
    'Prediction': 'When extrapolate shapes prediction',
    'Problem Solving': 'When extrapolate shapes problem solving',
    'Planning': 'When extrapolate shapes planning',
    'Inference': 'When extrapolate shapes inference',
  },
  'facilitate': {
    'Project Management': 'When you facilitate progress by removing obstacles',
    'Leadership': 'When good leaders facilitate rather than dictate',
    'Coordination': 'When true facilitation requires managing complex dynamics',
    'Teamwork': 'When one person facilitates collaboration between parts',
  },
  'false dichotomy': {
    'Logic': 'When false dichotomy shapes logic',
    'Nuance': 'When false dichotomy shapes nuance',
    'Critical Thinking': 'When false dichotomy shapes critical thinking',
    'Polarization': 'When false dichotomy shapes polarization',
  },
  'falsifiable': {
    'Critical Thinking': 'When falsifiable shapes critical thinking',
    'Science': 'When falsifiable shapes science',
    'Beliefs': 'When falsifiable shapes beliefs',
    'Learning': 'When falsifiable shapes learning',
  },
  'fealty': {
    'Loyalty': 'When fealty binds you beyond reason or convenience',
    'Honor': 'When you uphold fealty even when no one is watching',
    'Commitment': 'When fealty transforms commitment into a sacred vow',
    'Relationships': 'When relationships demand fealty that shapes who you become',
  },
  'flashpoint': {
    'Threshold': 'When flashpoint shapes threshold',
    'Crisis': 'When flashpoint shapes crisis',
    'Awareness': 'When flashpoint shapes awareness',
    'Prevention': 'When flashpoint shapes prevention',
  },
  'forlorn': {
    'Travel': 'When forlorn shapes travel',
    'Memory': 'When forlorn shapes memory',
    'Reading': 'When forlorn shapes reading',
    'Film': 'When forlorn shapes film',
  },
  'forthright': {
    'Communication': 'When forthright shapes communication',
    'Honesty': 'When forthright shapes honesty',
    'Courage': 'When forthright shapes courage',
    'Leadership': 'When forthright shapes leadership',
  },
  'frugal': {
    'Money': 'When frugal shapes money',
    'Relationships': 'When frugal shapes relationships',
    'Values': 'When frugal clarifies what truly matters',
    'Judgment': 'When frugal informs good judgment',
  },
  'furthermore': {
    'Presentations': 'When furthermore shapes presentations',
    'Meetings': 'When furthermore shapes meetings',
    'Public Speaking': 'When furthermore shapes public speaking',
    'Communication': 'When furthermore shapes communication',
  },
  'gaslighting': {
    'Manipulation': 'When gaslighting shapes manipulation',
    'Psychological': 'When gaslighting shapes psychological',
    'Awareness': 'When gaslighting shapes awareness',
    'Protection': 'When gaslighting shapes protection',
  },
  'gatekeeping': {
    'Access': 'When gatekeeping shapes access',
    'Exclusion': 'When gatekeeping shapes exclusion',
    'Control': 'When gatekeeping shapes control',
    'Belonging': 'When gatekeeping shapes belonging',
  },
  'gleam': {
    'First Meeting': 'When gleam shapes first meeting',
    'Conversation': 'When gleam shapes conversation',
    'Family Moment': 'When gleam shapes family moment',
    'Surprise': 'When gleam shapes surprise',
  },
  'granular': {
    'Problem-Solving': 'When granular shapes problem-solving',
    'Precision': 'When granular shapes precision',
    'Analysis': 'When granular shapes analysis',
    'Learning': 'When granular shapes learning',
  },
  'heathen': {
    'Identity': 'When you embrace being heathen to others',
    'Outsider': 'When heathen status reveals who belongs and who doesn\'t',
    'Culture': 'When cultural standards label some as heathen',
    'Perspective': 'When heathen influence makes you question whose norms matter',
  },
  'hedging': {
    'Communication': 'When hedging shapes communication',
    'Accountability': 'When hedging shapes accountability',
    'Courage': 'When hedging shapes courage',
    'Honesty': 'When hedging shapes honesty',
  },
  'hegemony': {
    'Power': 'When hegemony shapes power',
    'Culture': 'When hegemony shapes cultural moments',
    'Norms': 'When hegemony challenges convention',
    'Awareness': 'When hegemony shapes awareness',
  },
  'highlight': {
    'Communication': 'When highlight shapes communication',
    'Visibility': 'When highlight shapes visibility',
    'Leadership': 'When highlight shapes leadership',
    'Priorities': 'When highlight shapes priorities',
  },
  'honestly': {
    'Difficult Conversations': 'When honestly shapes difficult conversations',
    'Trust': 'When honestly shapes trust',
    'Vulnerability': 'When honestly shapes vulnerability',
    'Communication': 'When honestly shapes communication',
  },
  'impugn': {
    'Trust': 'When impugn shapes trust',
    'Criticism': 'When impugn shapes criticism',
    'Integrity': 'When impugn shapes integrity',
    'Conflict': 'When impugn shapes conflict',
  },
  'inchoate': {
    'Creativity': 'When inchoate shapes creativity',
    'Growth': 'When inchoate accelerates your growth',
    'Beginning': 'When inchoate shapes beginning',
    'Development': 'When inchoate accelerates your growth',
  },
  'incidental': {
    'Chance': 'When incidental shapes chance',
    'Discovery': 'When incidental shapes discovery',
    'Perspective': 'When incidental shapes perspective',
    'Attention': 'When incidental shapes attention',
  },
  'indicate': {
    'Signals': 'When indicate shapes signals',
    'Awareness': 'When indicate shapes awareness',
    'Strategy': 'When indicate shapes strategy',
    'Evidence': 'When indicate shapes evidence',
  },
  'ineffable': {
    'Spirituality': 'When ineffable shapes spirituality',
    'Art': 'When ineffable fuels creative expression',
    'Love': 'When ineffable shapes love',
    'Mystery': 'When ineffable shapes mystery',
  },
  'inquire': {
    'Job Search': 'When inquire shapes job search',
    'Networking': 'When inquire shapes networking',
    'First Impressions': 'When inquire shapes first impressions',
    'Professional Email': 'When inquire shapes professional email',
  },
  'insouciant': {
    'Confidence': 'When insouciant shapes confidence',
    'Freedom': 'When insouciant shapes freedom',
    'Attitude': 'When insouciant shapes attitude',
    'Literature': 'When insouciant shapes literature',
  },
  'instrumentalise': {
    'Relationships': 'When instrumentalise shapes relationships',
    'Ethics': 'When instrumentalise shapes ethics',
    'Respect': 'When instrumentalise shapes respect',
    'Work': 'When instrumentalise shapes work',
  },
  'intractable': {
    'Limits': 'When intractable shapes limits',
    'Problem-Solving': 'When intractable becomes key to solving the problem',
    'Planning': 'When intractable shapes planning',
    'Reflection': 'When intractable shapes reflection',
  },
  'invidious': {
    'Fairness': 'When invidious comparisons breed resentment and injustice',
    'Bias': 'When you recognize invidious bias hiding behind casual words',
    'Social Justice': 'When invidious systems unfairly discriminate against entire groups',
    'Ethics': 'When you refuse to make invidious judgments about others',
  },
  'irritability': {
    'Regulation': 'When irritability shapes regulation',
    'Stress': 'When irritability shapes stress',
    'Self-Care': 'When irritability shapes self-care',
    'Awareness': 'When irritability shapes awareness',
  },
  'issue': {
    'Crisis Management': 'When issue shapes crisis management',
    'Client Communication': 'When issue shapes client communication',
    'Spin': 'When issue shapes spin',
    'Professional': 'When issue shapes professional',
  },
  'justify': {
    'Accountability': 'When justify shapes accountability',
    'Reasoning': 'When justify shapes reasoning',
    'Stakeholders': 'When justify shapes stakeholders',
    'Values': 'When justify shapes values',
  },
  'ken': {
    'Learning': 'When ken shapes learning',
    'Science': 'When ken shapes science',
    'Philosophy': 'When ken shapes philosophy',
    'Culture': 'When ken shapes culture',
  },
  'kindly': {
    'Work Email': 'When you kindly request something but sound ice-cold instead',
    'Conflict': 'When saying kindly makes your message firm rather than polite',
    'Boundaries': 'When you ask someone to kindly stop crossing the line',
    'Professional Communication': 'When using kindly shifts your tone completely',
  },
  'lassitude': {
    'Fatigue': 'When lassitude shapes fatigue',
    'Emotion': 'When lassitude shapes emotion',
    'Resilience': 'When lassitude shapes resilience',
    'Health': 'When lassitude shapes health',
  },
  'latent': {
    'Potential': 'When latent shapes potential',
    'Growth': 'When latent shapes growth',
    'Self-Discovery': 'When latent shapes self-discovery',
    'Development': 'When latent shapes development',
  },
  'legitimacy': {
    'Authority': 'When legitimacy shapes authority',
    'Recognition': 'When legitimacy shapes recognition',
    'Power': 'When legitimacy shapes power',
    'Acceptance': 'When legitimacy shapes acceptance',
  },
  'leverage': {
    'Strategy': 'When leverage shapes strategy',
    'Business': 'When leverage shapes business',
    'Jargon': 'When leverage shapes jargon',
    'Communication': 'When leverage shapes communication',
  },
  'loaded': {
    'Language': 'When loaded shapes language',
    'Emotion': 'When loaded shapes emotion',
    'Bias': 'When loaded shapes bias',
    'Awareness': 'When loaded shapes awareness',
  },
  'logical fallacy': {
    'Critical Thinking': 'When logical fallacy shapes critical thinking',
    'Logic': 'When logical fallacy shapes logic',
    'Reasoning': 'When logical fallacy shapes reasoning',
    'Skepticism': 'When logical fallacy shapes skepticism',
  },
  'lugubrious': {
    'Literature': 'When lugubrious shapes literature',
    'Emotion': 'When lugubrious shapes emotion',
    'Atmosphere': 'When lugubrious shapes atmosphere',
    'Memory': 'When lugubrious shapes memory',
  },
  'moral hazard': {
    'Risk': 'When moral hazard shapes risk',
    'Economics': 'When moral hazard shapes economics',
    'Incentives': 'When moral hazard shapes incentives',
    'Policy': 'When moral hazard shapes policy',
  },
  'moralising': {
    'Judgment': 'When moralising shapes judgment',
    'Communication': 'When moralising shapes communication',
    'Humility': 'When moralising shapes humility',
    'Perspective': 'When moralising shapes perspective',
  },
  'naught': {
    'Project': 'When naught shapes project',
    'Relationship': 'When naught shapes relationship',
    'Goal': 'When naught shapes goal',
    'Creative Work': 'When naught shapes creative work',
  },
  'nebulous': {
    'Communication': 'When nebulous shapes communication',
    'Clarity': 'When nebulous shapes clarity',
    'Emotion': 'When nebulous shapes emotion',
    'Understanding': 'When nebulous shapes understanding',
  },
  'nonplussed': {
    'Surprise': 'When nonplussed shapes surprise',
    'Emotion': 'When nonplussed shapes emotion',
    'Reaction': 'When nonplussed shapes reaction',
    'Language': 'When nonplussed shapes language',
  },
  'normative': {
    'Values': 'When normative demonstrates real value',
    'Philosophy': 'When normative shapes philosophy',
    'Standards': 'When normative elevates quality',
    'Beliefs': 'When normative shapes beliefs',
  },
  'nuance': {
    'Communication': 'When nuance transforms what you say into what they understand',
    'Art': 'When layers of nuance reveal beauty beneath the surface',
    'Relationships': 'When you catch the nuance in someone\'s tone and respond with care',
    'Decision Making': 'When considering nuance prevents a rushed wrong choice',
  },
  'obdurate': {
    'Conflict': 'When someone becomes obdurate, compromise becomes impossible',
    'Character': 'When obdurate stubbornness hardens into rigid character',
    'Relationships': 'When you stay obdurate and watch the relationship crumble',
    'Growth': 'When obdurate refusal to change blocks all growth',
  },
  'obfuscation': {
    'Communication': 'When obfuscation shapes communication',
    'Clarity': 'When obfuscation shapes clarity',
    'Deception': 'When obfuscation shapes deception',
    'Awareness': 'When obfuscation brings genuine understanding',
  },
  'oblique': {
    'Communication': 'When oblique hints confuse instead of clarify',
    'Directness': 'When you choose oblique words to avoid conflict',
    'Relationships': 'When oblique criticism damages trust',
    'Courage': 'When courage means abandoning oblique approaches for truth',
  },
  'opaque': {
    'Understanding': 'When opaque brings genuine understanding',
    'Trust': 'When opaque shapes trust',
    'Communication': 'When opaque shapes communication',
    'Clarity': 'When opaque shapes clarity',
  },
  'ostensible': {
    'Truth': 'When ostensible shapes truth',
    'Deception': 'When ostensible shapes deception',
    'Relationships': 'When ostensible shapes relationships',
    'Insight': 'When ostensible shapes insight',
  },
  'othering': {
    'Exclusion': 'When othering shapes exclusion',
    'Awareness': 'When othering shapes awareness',
    'Social Dynamics': 'When othering shapes social dynamics',
    'Identity': 'When othering shapes identity',
  },
  'paradigm': {
    'Perspective': 'When paradigm shapes perspective',
    'Learning': 'When paradigm shapes learning',
    'Growth': 'When paradigm shapes growth',
    'Belief': 'When paradigm shapes belief',
  },
  'parochial': {
    'Culture': 'When parochial shapes culture',
    'Travel': 'When parochial shapes travel',
    'Perspective': 'When parochial shapes perspective',
    'Bias': 'When parochial shapes bias',
  },
  'parsimonious': {
    'Decision-Making': 'When parsimonious shapes decision-making',
    'Design': 'When parsimonious shapes design',
    'Efficiency': 'When parsimonious shapes efficiency',
    'Strategy': 'When parsimonious shapes strategy',
  },
  'paternalistic': {
    'Autonomy': 'When paternalistic shapes autonomy',
    'Authority': 'When paternalistic shapes authority',
    'Care': 'When paternalistic shapes care',
    'Control': 'When paternalistic shapes control',
  },
  'pedagogy': {
    'Education': 'When pedagogy shapes education',
    'Mentorship': 'When pedagogy shapes mentorship',
    'Self-Teaching': 'When pedagogy shapes self-teaching',
    'Skill Development': 'When pedagogy accelerates your growth',
  },
  'performative': {
    'Authenticity': 'When performative shapes authenticity',
    'Self-Examination': 'When performative shapes self-examination',
    'Sincerity': 'When performative shapes sincerity',
    'Action': 'When performative shapes action',
  },
  'perfunctory': {
    'Attention': 'When perfunctory shapes attention',
    'Respect': 'When perfunctory shapes respect',
    'Connection': 'When perfunctory deepens your relationships',
    'Authenticity': 'When perfunctory shapes authenticity',
  },
  'pithy': {
    'Writing': 'When pithy sentences cut through the clutter',
    'Communication': 'When you make your point pithy and people actually remember it',
    'Advice': 'When the most pithy advice hits harder than long lectures',
    'Wisdom': 'When pithy wisdom packs lifetimes into single sentences',
  },
  'plight': {
    'Social Issues': 'When you witness the plight of those without voice or power',
    'Current Events': 'When current events reveal the plight of entire communities',
    'Personal Experience': 'When your own plight teaches you empathy',
    'History': 'When historical plight echoes in today\'s struggles',
  },
  'polarisation': {
    'Division': 'When polarisation shapes division',
    'Extremes': 'When polarisation shapes extremes',
    'Conflict': 'When polarisation shapes conflict',
    'Society': 'When polarisation shapes cultural moments',
  },
  'preclude': {
    'Decisions': 'When preclude shapes decisions',
    'Limitations': 'When preclude shapes limitations',
    'Adaptation': 'When preclude shapes adaptation',
    'Constraints': 'When preclude shapes constraints',
  },
  'prevarication': {
    'Honesty': 'When prevarication tests your integrity',
    'Integrity': 'When prevarication tests your integrity',
    'Evasion': 'When prevarication shapes evasion',
    'Ethics': 'When prevarication shapes ethics',
  },
  'principled': {
    'Integrity': 'When principled tests your integrity',
    'Values': 'When principled shapes values',
    'Character': 'When principled shapes character',
    'Courage': 'When principled shapes courage',
  },
  'proficiency': {
    'Language': 'When proficiency shapes language',
    'Music': 'When proficiency shapes music',
    'Sports': 'When proficiency shapes sports',
    'Technical Skill': 'When proficiency sharpens your skills',
  },
  'projection': {
    'Self-Awareness': 'When projection shapes self-awareness',
    'Bias': 'When projection shapes bias',
    'Relationships': 'When projection deepens your relationships',
    'Emotions': 'When projection shapes emotions',
  },
  'quite': {
    'Cultural Differences': 'When quite shapes cultural differences',
    'International Work': 'When quite shapes international work',
    'Miscommunication': 'When quite shapes miscommunication',
    'Compliments': 'When quite shapes compliments',
  },
  'quoth': {
    'Literature': 'When quoth transforms ordinary speech into prophecy',
    'Wisdom': 'When they quoth wisdom that echoes through time',
    'Repetition': 'When people quoth the same phrase until it becomes ritual',
    'Prophecy': 'When words quoth become self-fulfilling prophecy',
  },
  'quotidian': {
    'Routine': 'When quotidian shapes routine',
    'Meaning': 'When quotidian shapes meaning',
    'Culture': 'When quotidian shapes culture',
    'Mindfulness': 'When quotidian shapes mindfulness',
  },
  'rather': {
    'Feedback': 'When rather shapes feedback',
    'Compliments': 'When rather shapes compliments',
    'Tone': 'When rather shapes tone',
    'Encouragement': 'When rather shapes encouragement',
  },
  'regarding': {
    'Client Email': 'When regarding shapes client email',
    'Team Communication': 'When regarding strengthens your team',
    'Professional Tone': 'When regarding shapes professional tone',
    'Formality': 'When regarding shapes formality',
  },
  'repudiate': {
    'Growth': 'When repudiate shapes growth',
    'Change': 'When repudiate shapes change',
    'Values': 'When repudiate shapes values',
    'Identity': 'When repudiate shapes identity',
  },
  'resignation': {
    'Agency': 'When resignation steals your sense of agency',
    'Motivation': 'When you notice resignation killing your motivation',
    'Change': 'When resignation convinces you change is impossible',
    'Mindset': 'When a mindset of resignation becomes your default',
  },
  'resilience': {
    'Recovery': 'When resilience shapes recovery',
    'Adaptation': 'When resilience shapes adaptation',
    'Strength': 'When resilience shapes strength',
    'Growth': 'When resilience accelerates your growth',
  },
  'resilient': {
    'Challenge': 'When resilient shapes challenge',
    'Growth': 'When resilient shapes growth',
    'Strength': 'When resilient shapes strength',
    'Adaptation': 'When resilient shapes adaptation',
  },
  'resolve': {
    'Decision Making': 'When resolve guides your important decisions',
    'Conflict': 'When resolve shapes conflict',
    'Clarity': 'When resolve shapes clarity',
    'Follow-through': 'When resolve shapes follow-through',
  },
  'respect': {
    'Boundaries': 'When respect shapes boundaries',
    'Disagreement': 'When respect shapes disagreement',
    'Relationships': 'When respect shapes relationships',
    'Acceptance': 'When respect shapes acceptance',
  },
  'retention': {
    'School Memory': 'When retention fades without practice or connection',
    'Life Lesson': 'When the retention of hard-earned lessons shapes who you become',
    'Professional Knowledge': 'When you improve retention by teaching what you learned',
    'Personal Story': 'When a story sticks through retention born of emotion',
  },
  'rewilding': {
    'Nature': 'When rewilding shapes nature',
    'Control': 'When rewilding shapes control',
    'Restoration': 'When rewilding shapes restoration',
    'Balance': 'When rewilding shapes balance',
  },
  'robust': {
    'Resilience': 'When robust shapes resilience',
    'Reliability': 'When robust shapes reliability',
    'Habits': 'When robust shapes habits',
    'Performance': 'When robust shapes performance',
  },
  'rumination': {
    'Coping': 'When rumination replaces action as your default response',
    'Awareness': 'When you catch yourself stuck in rumination spirals',
    'Habits': 'When the rumination habit wears grooves deeper each day',
    'Mental Health': 'When rumination becomes the prison your mind builds',
  },
  'salient': {
    'Reading': 'When one salient sentence reframes everything you thought you knew',
    'Writing': 'When you craft the salient point that captures attention first',
    'Memory': 'When salient details stick while everything else fades',
    'Learning': 'When the most salient moments become the ones you remember',
  },
  'sardonic': {
    'Humor': 'When sardonic shapes humor',
    'Communication': 'When sardonic shapes communication',
    'Tone': 'When sardonic shapes tone',
    'Personality': 'When sardonic shapes personality',
  },
  'scalability': {
    'Learning': 'When you discover scalability as the hard becomes easy',
    'Growth': 'When scalability accelerates your growth exponentially',
    'Efficiency': 'When scalability means you achieve more while spending less',
    'Mastery': 'When you reach scalability through deliberate practice',
  },
  'scalable': {
    'Principles': 'When scalable shapes principles',
    'Transfer': 'When scalable shapes transfer',
    'Systems': 'When scalable shapes systems',
    'Leadership': 'When scalable shapes leadership',
  },
  'sensible': {
    'Language Learning': 'When sensible shapes language learning',
    'Embarrassment': 'When sensible shapes embarrassment',
    'False Friends': 'When sensible shapes false friends',
    'Communication': 'When sensible shapes communication',
  },
  'significant': {
    'Presentations': 'When you say "significant results" to hide that the numbers are small',
    'Reports': 'When significant becomes a placeholder for precision you lack',
    'Data': 'When replacing significant with actual percentages reveals the truth',
    'Communication': 'When significant sounds impressive but communicates nothing',
  },
  'simple': {
    'Design': 'When simple shapes design',
    'Problem Solving': 'When simple shapes problem solving',
    'Creativity': 'When simple shapes creativity',
    'Work': 'When simple shapes work',
  },
  'smite': {
    'Revelation': 'When revelation smites you with undeniable truth',
    'Impact': 'When the impact smites with force that changes everything',
    'Divine': 'When something divine smites you into transformation',
    'Transformation': 'When you\'re smitten by moments that reshape who you are',
  },
  'social capital': {
    'Connections': 'When social capital shapes connections',
    'Community': 'When social capital shapes community',
    'Resources': 'When social capital shapes resources',
    'Support': 'When social capital shapes support',
  },
  'somewhat': {
    'Difficult Conversations': 'When somewhat shapes difficult conversations',
    'Feedback': 'When somewhat shapes feedback',
    'Relationships': 'When somewhat deepens your relationships',
    'Honesty': 'When somewhat shapes honesty',
  },
  'specious': {
    'Critical Thinking': 'When specious shapes critical thinking',
    'Reasoning': 'When specious shapes reasoning',
    'Deception': 'When specious shapes deception',
    'Skepticism': 'When specious shapes skepticism',
  },
  'speculative': {
    'Uncertainty': 'When speculative shapes uncertainty',
    'Decision Making': 'When speculative shapes decision making',
    'Risk': 'When speculative shapes risk',
    'Intuition': 'When speculative shapes intuition',
  },
  'stochastic': {
    'Uncertainty': 'When stochastic shapes uncertainty',
    'Patterns': 'When stochastic shapes patterns',
    'Observation': 'When stochastic shapes observation',
    'Risk': 'When stochastic shapes risk',
  },
  'suggest': {
    'Meetings': 'When suggest shapes meetings',
    'Leadership': 'When suggest shapes leadership',
    'Confidence': 'When suggest shapes confidence',
    'Decision Making': 'When suggest shapes decision making',
  },
  'support': {
    'Commitment': 'When support shapes commitment',
    'Action': 'When support shapes action',
    'Advocacy': 'When support shapes advocacy',
    'Teamwork': 'When support shapes teamwork',
  },
  'swain': {
    'Courtship': 'When swain shapes courtship',
    'Love Letters': 'When swain shapes love letters',
    'Traditions': 'When swain shapes traditions',
    'Gestures': 'When swain shapes gestures',
  },
  'sward': {
    'Childhood Place': 'When sward shapes childhood place',
    'Travel Memory': 'When sward shapes travel memory',
    'Park': 'When sward shapes park',
    'Natural Setting': 'When sward shapes natural setting',
  },
  'synergy': {
    'Team Project': 'When a synergy between teammates makes the final result better than anyone expected',
    'Collaboration': 'When genuine synergy emerges from working together with the right people',
    'Creative Work': 'When synergy between different creative skills produces something revolutionary',
    'Problem Solving': 'When synergy across different perspectives solves a problem no single approach could',
  },
  'tenuous': {
    'Relationships': 'When tenuous deepens your relationships',
    'Work': 'When tenuous shapes work',
    'Learning': 'When tenuous shapes learning',
    'Change': 'When tenuous shapes change',
  },
  'trade-off': {
    'Career': 'When trade-off shapes career',
    'Decision Making': 'When trade-off guides your important decisions',
    'Priorities': 'When trade-off clarifies what truly matters',
    'Strategy': 'When trade-off shapes strategy',
  },
  'undermine': {
    'Trust': 'When undermine shapes trust',
    'Power': 'When undermine shapes power',
    'Team Dynamics': 'When undermine shapes team dynamics',
    'Integrity': 'When undermine shapes integrity',
  },
  'understand': {
    'Empathy': 'When understand opens emotional understanding',
    'Listening': 'When understand shapes listening',
    'Emotional Support': 'When understand provides genuine support',
    'Friendship': 'When understand shapes friendship',
  },
  'unique': {
    'Feedback': 'When unique shapes feedback',
    'Art': 'When unique shapes art',
    'Creativity': 'When unique shapes creativity',
    'Communication': 'When unique shapes communication',
  },
  'utilize': {
    'Writing': 'When utilize shapes writing',
    'Communication': 'When utilize transforms how you speak',
    'Clarity': 'When utilize brings clarity',
    'Confidence': 'When utilize shapes confidence',
  },
  'verdant': {
    'Nature': 'When spring transforms the landscape into verdant abundance',
    'Travel': 'When you discover a verdant valley untouched by concrete',
    'Memory': 'When the verdant beauty of a place stays with you forever',
    'Beauty': 'When verdant greenery speaks directly to the soul',
  },
  'wane': {
    'Hobby': 'When wane shapes hobby',
    'Friendship': 'When wane shapes friendship',
    'Career Interest': 'When wane shapes career interest',
    'Belief': 'When wane shapes belief',
  },
  'wend': {
    'Journey': 'When you wend your way toward meaning',
    'Purpose': 'When your path gains purpose as you wend forward',
    'Path': 'When choosing to wend slowly rather than rush',
    'Future': 'When wending your way shapes who you become',
  },
  'wraith': {
    'Past Relationship': 'When wraith shapes past relationship',
    'Old Home': 'When wraith shapes old home',
    'Childhood Memory': 'When wraith awakens memory',
    'Lost Dream': 'When wraith shapes lost dream',
  },
  'wrath': {
    'Literature': 'When wrath shapes literature',
    'History': 'When wrath shapes history',
    'Mythology': 'When wrath shapes mythology',
    'Film': 'When wrath shapes film',
  },
  'yore': {
    'Family History': 'When yore marks a defining moment',
    'Historical Era': 'When yore marks a defining moment',
    'Mythology': 'When yore shapes mythology',
    'Old Customs': 'When yore shapes old customs',
  },
};

export default wordAnchorExamples;